### ISSUE TITLE
x86 library has text relocations, can't be used on Android 6

### ISSUE THREAD

**Issue by Viish** [cisco/openh264#2263]
When compiling openH264 for Android x86 using
make libraries -j4 OS=android ARCH=x86 NDKROOT=$(NDK_PATH) TARGET=android-19

The generated libopenh264.so has text relocation issue that causes Android 6 to crash when trying to load it. You can check using:
readelf -d -r libopenh264.so | grep TEXT

I've tried with commit id 21ad38f430f62d11ff0c02f245a1df904f89f99a, and I'm using NDK r10e-rc4 on Linux 64bits.

**Comment by zhangguowei** [comment]
Now you solve it？I also encountered the same problem

**Comment by huili2** [comment]
Thanks for your information. It is caused by assembly incompatible. We're now fixing it. Will post here if it is done.

**Comment by GuangweiWang** [comment]
hi, @Viish . could you please give more info about you build environment? e.g. which platform you build on , your os version, gcc/clang version ... 
thanks very much

**Comment by huili2** [comment]
It has been fixed in #2611.

**Comment by SukumarPK** [comment]
Hi, I am still facing this problem with libopenh264.so. I have attached a screenshot of this issue tried in Nexus 5 emulator. 
Build Tools version:25
Target SDK version:21
![nexus 5 warning](https://cloud.githubusercontent.com/assets/25075748/22280761/e522c12c-e2f8-11e6-8232-7114d0d7ca25.png)
It showed as a warning in Nexus 5 emulator but it physical Nexus 5 and other devices, the app still crashing.

**Comment by GuangweiWang** [comment]
hi, @SukumarPK 

the fix should be enabled by a macro, but this macro is disable on default. if you want to build libopenh264.so without text-relocation issue, you can append this option ENABLEPIC=Yes on your command line. e.g. make ARCH=x86 ENABLEPIC=Yes OS=android NDKROOT=$ANDROID_NDK TARGET=android-24

**Comment by omar-othmann** [comment]
@GuangweiWang I did it and did not work
If it works with you please post it on github.

Thank you

**Comment by omar-othmann** [comment]
![default](https://user-images.githubusercontent.com/34454535/35211898-919d8f32-ff58-11e7-8832-e532c7249533.PNG)
![default](https://user-images.githubusercontent.com/34454535/35211905-987f76bc-ff58-11e7-84d1-3576c13f6c36.PNG)

 libopenh264.so has text relocation

**Comment by GuangweiWang** [comment]
if you try this: "readelf -d -r libopenh264.so | grep TEXT", is there any text relocation information?

**Comment by omar-othmann** [comment]
![default](https://user-images.githubusercontent.com/34454535/35219770-2d7124f8-ff74-11e7-8378-78b7bd800df1.PNG)

result

**Comment by omar-othmann** [comment]
@GuangweiWang  Android studio Error debug:
![default](https://user-images.githubusercontent.com/34454535/35220002-fcc7b67c-ff74-11e7-84b3-db6048da7c11.PNG)

Thank you for reply!

**Comment by omar-othmann** [comment]
It works without problems on android-16 -> android-21

and not working on android-22 -> android-26

**Comment by omar-othmann** [comment]
i have successfully ignored the problem

When you build the project a file comes out with libopenh264.so named
libopenh264.a
You copy this file and place it in a new folder
Create a file named in new folder
Android.mk
Type in it:
LOCAL_PATH: = $ (call my-dir)

include $ (CLEAR_VARS)

LOCAL_CPP_EXTENSION: = .cc

LOCAL_SRC_FILES: = libopenh264.a

LOCAL_EXPORT_C_INCLUDES: = $ (LOCAL_PATH) / include
LOCAL_C_INCLUDES + = $ (LOCAL_PATH) / include

LOCAL_MODULE: = libopenh264
LOCAL_MODULE_TAGS: = optional

include $ (BUILD_SHARED_LIBRARY)
#include $ (BUILD_STATIC_LIBRARY)
Then create the Application.mk file
Type in it:
APP_ABI: = x86
APP_PLATFORM: = android-24
NDK_TOOLCHAIN_VERSION: = clang

right Now:
cd / path / youfolder
and:
ndk-build
If you encounter a problem.. send mail to: ceunix@gmail.com and i send  libopenh264.so work on android6 x86 for you

**Comment by GuangweiWang** [comment]
many thanks for the detailed information!
I will try to reproduce this issue, could you please provide this two information to me?
1. the commit ID of you your openh264 source code.
2. your NDK version

thanks!

**Comment by omar-othmann** [comment]
Hi @GuangweiWang 
Ndk: android-ndk-r9c
Source code: https://github.com/cisco/openh264

[android_libopenh264_x86.zip](https://github.com/cisco/openh264/files/1656011/android_libopenh264_x86.zip)

**Comment by omar-othmann** [comment]
But I have converted the libopenh264.a file from Windows and not from Linux

Windows ANDROID NDK: android-ndk-r15c
C:\Users\Omar>ndk-build -v
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i586-pc-mingw32

C:\Users\Omar>

**Comment by omar-othmann** [comment]
There error. Some methods are not included in the libopenh264.so. So I did not succeed

but i have find text relocations in libopenh264.so It can help you find a solution to this problem:

![default](https://user-images.githubusercontent.com/34454535/35293661-aadd3c0a-0074-11e8-8b93-fe8e51004a4b.PNG)
![default](https://user-images.githubusercontent.com/34454535/35293702-ce613d20-0074-11e8-8019-d6276e32e2e2.PNG)


So.. libopenh264 contains 967 Relocation

**Comment by GuangweiWang** [comment]
that functions you mentioned are the system functions.

how do you build the libopenh264.so?
if you build both libopenh264.a and libopenh264.so on Linux platform, is there any text relocation issue?

**Comment by omar-othmann** [comment]
Yes is there text relocation for x86 only. I don't know why

Can you try it?

**Comment by omar-othmann** [comment]
Why i build libopenh264.a to libopenh264.so there method missing

**Comment by omar-othmann** [comment]
![35219770-2d7124f8-ff74-11e7-8378-78b7bd800df1](https://user-images.githubusercontent.com/34454535/35334947-56c549f0-0114-11e8-9678-f242c947c61f.PNG)

**Comment by omar-othmann** [comment]
with asm
![default](https://user-images.githubusercontent.com/34454535/35439281-5913d41a-029a-11e8-9405-7cbbe5b7cd21.PNG)

-no-asm: Does not execute output.
![default](https://user-images.githubusercontent.com/34454535/35439315-7b0f6174-029a-11e8-88b8-a3610503d83c.PNG)

**Comment by Nan0fm** [comment]
@GuangweiWang or @huili2 
Hi =)
Is it already solved? I got the same errors..(

**Comment by GuangweiWang** [comment]
I can not reproduce this issue on my platform, could you please provide more information?
1. the commit ID of you your openh264 source code.
2. your NDK version
3. your OS info.
thanks!

**Comment by Nan0fm** [comment]
@GuangweiWang 
Hi =) thank you for quick response
I've refreshed lib on my project (I previously used the older version), now I use the latest vers ( latest **commit** de0537b  ) 
**NDK** vers r16 
**OS**: I've use ubuntu 16.04 LTS (64bit) on the VirtualBox for build the lib (native OS - Win10)

After that I've build the library with command

`usr@usrComputer:/media/sf_projects/proj3/android/libs/openh264-1.7.0$ export NDK_ROOT=~/Android/Sdk/ndk-bundle/
usr@usrComputer:/media/sf_projects/proj3/android/libs/openh264-1.7.0$ make OS=android NDKROOT=$NDK_ROOT TARGET=x86
/home/usr/Android/Sdk/ndk-bundle//toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -O3 -DNDEBUG -DHAVE_NEON -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -DANDROID_NDK -fpic --sysroot=/home/ann/Android/Sdk/ndk-bundle//platforms/android-12/arch-arm -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -Dandroid_getCpuIdArm=wels_getCpuIdArm -Dandroid_setCpuArm=wels_setCpuArm -Dandroid_getCpuCount=wels_getCpuCount -Dandroid_getCpuFamily=wels_getCpuFamily -Dandroid_getCpuFeatures=wels_getCpuFeatures -Dandroid_setCpu=wels_setCpu  -I/home/usr/Android/Sdk/ndk-bundle//sources/android/cpufeatures -c -o codec/common/src/cpu-features.o /home/usr/Android/Sdk/ndk-bundle//sources/android/cpufeatures/cpu-features.c
In file included from /home/usr/Android/Sdk/ndk-bundle//sources/android/cpufeatures/cpu-features.c:64:0:
/home/usr/Android/Sdk/ndk-bundle//sources/android/cpufeatures/cpu-features.h:31:23: fatal error: sys/cdefs.h: No such file or directory
 #include <sys/cdefs.h>
                       ^
compilation terminated.
build/platform-android.mk:96: recipe for target 'codec/common/src/cpu-features.o' failed
make: *** [codec/common/src/cpu-features.o] Error 1
usr@usrComputer:/media/sf_projects/proj3/android/libs/openh264-1.7.0$
 `
p.s. also I received output as @omar-othmann on Jan 26 , but I've received it when I compile your lib with other libs in my project

**Comment by Nan0fm** [comment]
@GuangweiWang 
sorry, previous answer was without ENABLEPIC. but even if I add this params, output is equal 
`usr@usrComputer:/media/sf_projects/proj3/android/libs/openh264$ export NDK_ROOT=~/Android/Sdk/ndk-bundle/usr@usrComputer:/media/sf_projects/proj3/android/libs/openh264$ make OS=android ENABLEPIC=YES NDKROOT=$NDK_ROOT TARGET=x86
/home/usr/Android/Sdk/ndk-bundle//toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc -O3 -DNDEBUG -DHAVE_NEON -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -DANDROID_NDK -fpic --sysroot=/home/usr/Android/Sdk/ndk-bundle//platforms/android-12/arch-arm -MMD -MP -DGENERATED_VERSION_HEADER -I./codec/api/svc -I./codec/common/inc -Icodec/common/inc -Dandroid_getCpuIdArm=wels_getCpuIdArm -Dandroid_setCpuArm=wels_setCpuArm -Dandroid_getCpuCount=wels_getCpuCount -Dandroid_getCpuFamily=wels_getCpuFamily -Dandroid_getCpuFeatures=wels_getCpuFeatures -Dandroid_setCpu=wels_setCpu  -I/home/usr/Android/Sdk/ndk-bundle//sources/android/cpufeatures -c -o codec/common/src/cpu-features.o /home/usr/Android/Sdk/ndk-bundle//sources/android/cpufeatures/cpu-features.c
In file included from /home/usr/Android/Sdk/ndk-bundle//sources/android/cpufeatures/cpu-features.c:64:0:
/home/usr/Android/Sdk/ndk-bundle//sources/android/cpufeatures/cpu-features.h:31:23: fatal error: sys/cdefs.h: No such file or directory
 #include <sys/cdefs.h>
                       ^
compilation terminated.
build/platform-android.mk:96: recipe for target 'codec/common/src/cpu-features.o' failed
make: *** [codec/common/src/cpu-features.o] Error 1
usr@usrComputer:/media/sf_projects/proj3/android/libs/openh264$ 
`

**Comment by GuangweiWang** [comment]
thanks for your information. I will try this.

**Comment by Nan0fm** [comment]
After swimming through the internet, I'm trying this, but still got the same errors

$  export NDK_PATH=~/Android/Ndk/android-ndk-r16b/
$  make OS=android NDKROOT=$NDK_PATH TARGET=android-27 ARCH=x86 NDKLEVEL=27
$  make OS=android NDKROOT=$NDK_PATH TARGET=android-27 ARCH=x86 NDKLEVEL=27 clean
$  make OS=android NDKROOT=$NDK_PATH TARGET=android-27 ARCH=x86 NDKLEVEL=27
$  sudo apt-get install libc6
$  sudo apt-get install libc6-dev
$ apt-file find cdefs.h
$  make OS=android NDKROOT=$NDK_PATH TARGET=android-27 ARCH=x86 NDKLEVEL=27

**Comment by Nan0fm** [comment]
@GuangweiWang 
Hi =)
Have you already tried my case?)
Or may be you can say your environment, and I'll try to reproduce in new environment

**Comment by Nan0fm** [comment]
@huili2 
May be you can help me?

**Comment by huili2** [comment]
@Nan0fm GuangweiWang is reviewing on this. :)

**Comment by GuangweiWang** [comment]
hi, @Nan0fm 
I built the libopenh264.so with the same version NDK and Linux platform. there is not "text relocation" issue on libopenh264.so. 

I attach my build step, this may help you.

![1334_3542](https://user-images.githubusercontent.com/11676737/39227028-e1001332-4888-11e8-9f66-da0895bc6465.png)
![1330_2522](https://user-images.githubusercontent.com/11676737/39227031-e53c096a-4888-11e8-8b26-ddf5d0578a75.png)

**Comment by GuangweiWang** [comment]
@Nan0fm 
did you modify the default Makefile or build script?

**Comment by GuangweiWang** [comment]
@omar-othmann 
did you resolve your problem?

**Comment by Nan0fm** [comment]
@GuangweiWang 
Thanks for response =)
I just tried this. There is output

usr@usrComputer:/media/sf_projects/proj3/android/libs/openh264$ export NDK_PATH=~/Android/Ndk/android-ndk-r16b/
usr@usrComputer:/media/sf_projects/proj3/android/libs/openh264$ make OS=android ARCH=x86 ENABLEPIC=YES NDKROOT=$NDK_PATH TARGET=android-27 SYSROOT=$NDK_PATH/sysroot
sh ./codec/common/generate_version.sh ./
Keeping existing codec/common/inc/version_gen.h
cd ./codec/build/android/dec && /home/usr/Android/Ndk/android-ndk-r16b//ndk-build -B APP_ABI=x86 && android update project -t android-27 -p . && ant debug
Android NDK: android-12 is unsupported. Using minimum supported version android-14.    
Android NDK: WARNING: APP_PLATFORM android-14 is higher than android:minSdkVersion 12 in ./AndroidManifest.xml. NDK binaries will *not* be comptible with devices older than android-14. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.    
make[1]: Entering directory `/media/sf_projects/proj3/android/libs/openh264/codec/build/android/dec'
[x86] Prebuilt       : libopenh264.so <= jni/../../../../../
make[1]: Warning: File `libs/x86' has modification time 0,79 s in the future
[x86] Install        : libopenh264.so => libs/x86/libopenh264.so
[x86] Compile++      : welsdecdemo <= h264dec.cpp
[x86] Compile++      : welsdecdemo <= read_config.cpp
[x86] Compile++      : welsdecdemo <= d3d9_utils.cpp
[x86] Compile++      : welsdecdemo <= myjni.cpp
[x86] Prebuilt       : libstlport_shared.so <= <NDK>/sources/cxx-stl/stlport/libs/x86/
[x86] SharedLibrary  : libwelsdecdemo.so
[x86] Install        : libwelsdecdemo.so => libs/x86/libwelsdecdemo.so
[x86] Install        : libstlport_shared.so => libs/x86/libstlport_shared.so
make[1]: warning:  Clock skew detected.  Your build may be incomplete.
make[1]: Leaving directory `/media/sf_projects/proj3/android/libs/openh264/codec/build/android/dec'
/bin/sh: 1: android: not found
build/platform-android.mk:71: recipe for target 'decdemo' failed
make: *** [decdemo] Error 127
usr@usrComputer:/media/sf_projects/proj3/android/libs/openh264$

**Comment by Nan0fm** [comment]
@GuangweiWang 
okay, i just added sdk path to PATH variable

usr@usrComputer:/media/sf_projects/proj3/android/libs/openh264$ export ANDROID_HOME=~/Android/Sdk
usr@usrComputer:/media/sf_projects/proj3/android/libs/openh264$ export PATH=$ANDROID_HOME/tools:$PATH
usr@usrComputer:/media/sf_projects/proj3/android/libs/openh264$ export PATH=$ANDROID_HOME/platform-tools:$PATH
usr@usrComputer:/media/sf_projects/proj3/android/libs/openh264$ make OS=android ARCH=x86 ENABLEPIC=Yes NDKROOT=$NDK_PATH TARGET=android-27 SYSROOT=$NDK_PATH/sysroot
sh ./codec/common/generate_version.sh ./
Keeping existing codec/common/inc/version_gen.h
cd ./codec/build/android/dec && /home/usr/Android/Ndk/android-ndk-r16b//ndk-build -B APP_ABI=x86 && android update project -t android-27 -p . && ant debug
Android NDK: android-12 is unsupported. Using minimum supported version android-14.    
Android NDK: WARNING: APP_PLATFORM android-14 is higher than android:minSdkVersion 12 in ./AndroidManifest.xml. NDK binaries will *not* be comptible with devices older than android-14. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md for more information.    
make[1]: Entering directory `/media/sf_projects/proj3/android/libs/openh264/codec/build/android/dec'
[x86] Prebuilt       : libopenh264.so <= jni/../../../../../
make[1]: Warning: File `libs/x86' has modification time 0,0035 s in the future
[x86] Install        : libopenh264.so => libs/x86/libopenh264.so
[x86] Compile++      : welsdecdemo <= h264dec.cpp
[x86] Compile++      : welsdecdemo <= read_config.cpp
[x86] Compile++      : welsdecdemo <= d3d9_utils.cpp
[x86] Compile++      : welsdecdemo <= myjni.cpp
[x86] Prebuilt       : libstlport_shared.so <= <NDK>/sources/cxx-stl/stlport/libs/x86/
[x86] SharedLibrary  : libwelsdecdemo.so
[x86] Install        : libwelsdecdemo.so => libs/x86/libwelsdecdemo.so
[x86] Install        : libstlport_shared.so => libs/x86/libstlport_shared.so
make[1]: warning:  Clock skew detected.  Your build may be incomplete.
make[1]: Leaving directory `/media/sf_projects/proj3/android/libs/openh264/codec/build/android/dec'
*************************************************************************
The "android" command is deprecated.
For manual SDK, AVD, and project management, please use Android Studio.
For command-line tools, use tools/bin/sdkmanager and tools/bin/avdmanager
*************************************************************************
Invalid or unsupported command "update project -t android-27 -p ."

Supported commands are:
android list target
android list avd
android list device
android create avd
android move avd
android delete avd
android list sdk
android update sdk
build/platform-android.mk:71: recipe for target 'decdemo' failed
make: *** [decdemo] Error 2
ann@annComputer:/media/sf_vWorkspace/old/openh/openh264$

**Comment by Nan0fm** [comment]
@GuangweiWang 
or if use "readelf" command

usr@usrComputer:/media/sf_projects/proj3/android/libs/openh264$ readelf -d -r libopenh264.so | grep TEXT
 0x00000016 (TEXTREL)                    0x0
 0x0000001e (FLAGS)                      TEXTREL BIND_NOW
usr@usrComputer:/media/sf_projects/proj3/android/libs/openh264$

**Comment by omar-othmann** [comment]
@GuangweiWang Hi dude, 
You said you did not encounter problems during the creation .. Please upload the file in order to download it. The problem ends

**Comment by omar-othmann** [comment]
@GuangweiWang My problem is not solved yet, I've done it without text relocations. But during audio playback an error appears in AudioDevice
I did not remember the exact type of error
but i have testing on real device like:
Samsung S8 +
- Samsung J5

Sasmung S8 + arm64-v8a
its work with out error

i Think the problem on Nexus 5 emulator.

**Comment by omar-othmann** [comment]
Samusng J5 is Quad-core, 1200 MHz, ARM Cortex-A53, 64-bit

and its work with out error. but i don't know the phone is load library from x64 folder or x86_64 folder

**Comment by Nan0fm** [comment]
@omar-othmann 
Yes, your case without error cause it happens only on x86 architecture and you trying it for another arch

**Comment by omar-othmann** [comment]
@Nan0fm maybe. but i have x64 with out text relocations, its work on Nexus 5, but i got error on AudioDevice wait i make screenshot.

**Comment by omar-othmann** [comment]
`D/PjSipLogWriter: 13:31:56.775 android_jni_de  ......Creating Android JNI stream
D/PjSipLogWriter: 13:31:56.839 android_jni_de  ......Using audio input source : 7
E/AudioRecord: AudioFlinger could not create record track, status: -1
E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -1.
E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
D/PjSipLogWriter: 13:31:56.864 android_jni_de  ......Failure in initializing audio record.
D/PjSipLogWriter: 13:31:56.864 android_jni_de  ......Trying the default audio source.
E/AudioRecord: AudioFlinger could not create record track, status: -1
E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -1.
E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
D/PjSipLogWriter: 13:31:56.878 android_jni_de  ......Failure in initializing audio record.
D/PjSipLogWriter: 13:31:56.878 android_jni_de  ......Destroying Android JNI stream...`




![default](https://user-images.githubusercontent.com/34454535/39249049-03c3dc0e-489e-11e8-840c-0be338a3f622.PNG)

**Comment by omar-othmann** [comment]
@Nan0fm  its work for me now ;)

**Comment by omar-othmann** [comment]
[libopenh264.zip](https://github.com/cisco/openh264/files/1947226/libopenh264.zip)

try it.... libopenh264.so for x86_x32 with out text relocations.

**Comment by GuangweiWang** [comment]
@Nan0fm 
please using "ENABLEPIC=Yes" to avoid text relocation.

**Comment by Nan0fm** [comment]
@GuangweiWang 
Thank you very much =)
Everything works fine and without text relocation on x86 😃

**Comment by GuangweiWang** [comment]
@Nan0fm 
Welcome.

**Comment by GuangweiWang** [comment]
@omar-othmann 
as your comments, I think you have solved your problem. it works for you now,  is it right?

**Comment by hbli** [comment]
![image](https://user-images.githubusercontent.com/3877088/48691363-2e9db580-eb87-11e8-9665-159f910426b8.png)
I had the same TEXT RELOCATION problem with x86 library. I was using libopen264.a to build another .so file.

@GuangweiWang 
I follow your procedure to try to build libopen264.so. But I got a error. See the screenshot.

**Comment by GuangweiWang** [comment]
@hbli 
can you open another issue to describe your problem? this issue is hard to track as too many comments. thanks.

**Comment by omar-othmann** [comment]
@GuangweiWang yes it's work for me, i have upload zip file to download it:
https://github.com/cisco/openh264/files/1947226/libopenh264.zip

**Comment by omar-othmann** [comment]
@hbli try zip file!

**Comment by hbli** [comment]
@omar-othmann Thank you. Is it x86 or x86_64?

**Comment by omar-othmann** [comment]
@hbli wait i upload for all arm

**Comment by omar-othmann** [comment]
@hbli so this zip file it's work from api 21 to 28, and it's work on Nexus 5 emulator,
download:
http://download.nibiru-x.com/jniLibs.zip

file is big i can't passt here!

**Comment by huili2** [comment]
Close this one since too long ago. If we have similar issues, please create a new issue.
