### ISSUE TITLE
Decoded B-frame buffer can be overwritten by next decoding frame

### ISSUE THREAD

**Issue by xiaotiansf** [cisco/openh264#3079]
In ffmpeg, it calls DecodeFrame2 once for each frame. However the decoded picture may not be ready immediately after the call (pDstInfo->iBufferStatus = 0). This is not a problem when B-frame decoding is not supported. 

The problem comes when B-frame decoding is supported:
The last decoded non-reference B-frame (pDstInfo->iBufferStatus = 0 after the call DecodeFrame2 ) (so it is disposable) buffer could be overwritten by next decoding frame because decoder thinks no-body refers to the B-frame.

So the correct way to do in ffmpeg is to call DecodeFrameNoDelay which contains two calls of DecodeFrame2. The second call allows to release the ready non-reference B-frame to be released immediately to prevent its buffer to be overwritten by next decoding frame.

Could someone provide help regarding this issue? Maybe there is a better solution?

@mstorsjo I am wondering that the issue in your test asset https://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_h264.mov. has something to do with this.

Thanks.

**Comment by mstorsjo** [comment]
If this is the case, the API of OpenH264 is wrong and you have the function names swapped.

If I want reordered frames, I should not call a function named DecodeFrameNoDelay. A function named DecodeFrameNoDelay should return the latest decoded frame directly without reordering, while the normal function that a caller is supposed to use, DecodeFrame2, should do reordering and generally do the right thing for users.

This would make things work for all existing users of OpenH264 even when encountering B-frames, without requiring them to change anything. If you require callers to suddenly start calling a different API, especially only if the bitstream uses a specific feature, the API is wrong/broken/unnecessarily complex.

**Comment by mstorsjo** [comment]
I can confirm that things do seem to work if using DecodeFrameNoDelay instead of DecodeFrame2, but that is not a change that you should force on all users of OpenH264. This is a detail that a decoder library should handle internally, and it is a failure of the library if it requires the callers to use a different API. And the DecodeFrameNoDelay function is completely and utterly misnamed right now.

**Comment by xiaotiansf** [comment]
@mstorsjo Make sense and I'll look for an internal solution within the library then.

**Comment by xiaotianshicomcast** [comment]
This buffer overwritten issue has been resolved by my code update in #PR3080

**Comment by mstorsjo** [comment]
The changes in PR #3080 has not fixed the issue when using DecodeFrame2 at all. Since commit 5eba56f693e5ab52a0122bd992abeced524ebf36 decoding with DecodeFrame2 returns lots of errors - you can e.g. try with https://download.blender.org/peach/bigbuckbunny_movies/big_buck_bunny_480p_h264.mov.

And were there any change so that DecodeFrame2 actually returns the frames in the correct, reordered order which should be the default for any existing caller?

**Comment by xiaotiansf** [comment]
@mstorsjo I'll take a look.

**Comment by xiaotiansf** [comment]
@mstorsjo Thanks a lot and I'll try to fix the issue without using DecodeFrameNoDelay.

**Comment by xiaotiansf** [comment]
@mstorsjo 
I have tested with both DecodeFrameNoDelay and DecodeFrame2 (only) on latest openh264/master branch and I got identical yuv binary output files using your short asset https://martin.st/temp/big_buck_bunny_480p_h264_cut30.mov.

**Comment by xiaotiansf** [comment]
@mstorsjo Thanks a lot for your input.

**Comment by thaytan** [comment]
I can confirm that using DecodeFrame2 produces fewer frames with that sample for me - in fact only 3 when testing with GStreamer. I think that's a problem in the sense that existing code expects DecodeFrame2 to produce all frames, but possibly with a 1 frame delay between frame input and output. 

It shouldn't lose frames and fail to decode now that B frames are introduced.
