### ISSUE TITLE
Decoder picture queue ran out of space

### ISSUE THREAD

**Issue by kawan-test** [cisco/openh264#3872]
When I test an use case of playback received frames on my target from remote rtsp streaming server, the decoder picture queue ran out of space. The error is below
Error:DecodeCurrentAccessUnit()::::::PrefetchPic ERROR, pSps->iNumRefFrames:4.
Info:ResetDecoder(), context error code is 16384

static inline int32_t GetTargetRefListSize (PWelsDecoderContext pCtx) {
... 
   } else {
    iNumRefFrames = pCtx->pSps->iNumRefFrames + 2;
...

In my test case, the iNumRefFrames =4, so the queue size is 6.

There is a comment in WelsRequestMem() saying that the queue size will be pSps->iNumRefFrames x 2.

iPicQueueSize = GetTargetRefListSize (pCtx); // adaptive size of picture queue, = (pSps->iNumRefFrames x 2)

I increased the queue size with the formula pCtx->pSps->iNumRefFrames * 2, the queue size is 8 in my case and the issue disappeared .

So the comment and actual code does not match. 
Should we use pCtx->pSps->iNumRefFrames * 2?  Or can we increase the buffer size like 
    iNumRefFrames = pCtx->pSps->iNumRefFrames + 4;

I am using QNX in my test target. h264 version is 2.4.1.

**Comment by tyan0** [comment]
If you could provide sample video which can reproduce the issue, it would help.

**Comment by kawan-test** [comment]
I used this sample video https://dvdloc8.com/clip.php?movieid=12167&clipid=3

**Comment by kawan-test** [comment]
I tried iNumRefFrames = pCtx->pSps->iNumRefFrames + 4;  It solves the issue as well.

**Comment by tyan0** [comment]
Thanks for sample video. Where does the problem occur? (Time or frame?)

**Comment by kawan-test** [comment]
It is not fixed time. Most of time is around 10 seconds.

**Comment by tyan0** [comment]
Thanks for the information. I could reproduce the issue with openh264 v2.4.1, however, could not with v2.5.0, or later. i.e. the issue was already fixed.

**Comment by kawan-test** [comment]
I will try against 2.6.0

**Comment by kawan-test** [comment]
I am still seeing the issue with 2.6.0 if I do not increase the picture queue size.

**Comment by tyan0** [comment]
What kind of player are you using? I tested with ffplay and mpv but the issue could not be reproduced. Does libopenh264 run in QNX via some player?

**Comment by kawan-test** [comment]
We have our own developed player using libopenh264.

**Comment by tyan0** [comment]
Do you use multi-threading decoding? If so, how many threads do you specify?

**Comment by glamberson** [comment]
I hit this exact issue independently, on openh264 2.6.0 (ABI 8) via the Rust bindings (openh264 0.9.8 / openh264-sys2 0.9.8), decoding H.264 my own VA-API encoder produces. My reproduction is fully deterministic and narrows down the trigger tyan0 was asking about.

My encoder emits an SPS with max_num_ref_frames=1 (single-reference IPPP, a common choice for low-latency screen sharing). Decoding with the default single-threaded config (num_threads=0), the picture queue is sized 1 + 2 = 3 slots. The 4th frame of every GOP overflows it: PrefetchPic fails with context error code 16384 (dsOutOfMemory), which resets the decoder and clears its SPS/PPS-seen state. Every subsequent P-slice in that GOP then fails with error code 16 (dsNoParamSets), since it legitimately carries no parameter sets of its own, until the next IDR resends SPS/PPS and reallocates a fresh 3-slot queue. This repeats identically every GOP, 100 percent reproducible, not player- or platform-specific.

I cross-validated by decoding the identical bytes with ffmpeg's own H.264 decoder: every frame decodes cleanly with zero errors, and the output is visually correct. The bitstream is valid. The queue-size formula in GetTargetRefListSize (iNumRefFrames + 2) still does not match the x2 the surrounding comments and WelsRequestMem describe, confirmed against current master.

Low max_num_ref_frames values look like an under-tested corner of this formula, since most encoders default to more references than 1. Is iNumRefFrames * 2 the intended fix, matching the existing comments, or should it be derived from something like max_dec_frame_buffering per the H.264 spec instead? I am looking at preparing a PR for this.

**Comment by glamberson** [comment]
Root-caused this. It's a genuine reference-count leak, not a queue-size/formula problem — neither of the fixes discussed earlier in this thread (`iNumRefFrames * 2`, `iNumRefFrames + 4`) actually close it; they just take longer to exhaust.

`BufferingReadyPicture()` (`welsDecoderExt.cpp`) pins the single-threaded "previous decoded picture" for error-concealment use:
```
if (GetThreadCount(pCtx) <= 1) ++pPrevPic->iRefCount;
```
Nothing ever releases that pin. `DecodeCurrentAccessUnit()` (`decoder_core.cpp`) overwrites `pLastDecPicInfo->pPreviousDecodedPictureInDpb` on every subsequent frame without decrementing the outgoing picture's `iRefCount` first. Every decoded picture leaks one picture-queue slot, permanently, until an IDR resets state. This explains why maintainers using ffplay/mpv (multi-threaded by default) couldn't reproduce past 2.5.0, while single-threaded callers keep hitting it — it's threading-mode-dependent, not version-dependent.

Fix is a symmetric decrement before the pointer is overwritten, gated the same way the pin itself is (`iThreadCount <= 1`). Validated against a real captured bitstream (45 pictures, `max_num_ref_frames=1`, two IDR cycles): fails at picture 3 without the fix (matches the `dsOutOfMemory`/`dsNoParamSets` pattern reported here), 168/168 clean with it, on the full original clip. Full upstream test suite (`processing`/`common`/`encoder`/`decoder`/`api`, including the error-concealment tests) passes unchanged with the fix applied.

Working on a PR with a regression test.
